//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_Autosaver.Properties {
    using System;
    using System.Collections.Generic;
    using System.Linq;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAI_Autosaver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 30,60,120,300,600,900,1800,3600,7200.
        /// </summary>
        internal static int[] ItemsBackupDelays {
            get {
                return ResourceManager.GetString("ItemsBackupDelays", resourceCulture).Split(',').Select(x => int.Parse(x)).ToArray();
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sai=Paint Tool Sai 1,sai2=Paint Tool Sai 2.
        /// </summary>
        internal static Dictionary<string, string> ItemsSaiVersions {
            get {
                return ResourceManager.GetString("ItemsSaiVersions", resourceCulture).Split(',').Select(x => x.Split('=')).ToDictionary(x => x[0], x1 => x1[1]);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ShadelessFox/PaintToolSaver.
        /// </summary>
        internal static string UpdaterRepo {
            get {
                return ResourceManager.GetString("UpdaterRepo", resourceCulture);
            }
        }
    }
}
