//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI_Autosaver.Properties {
    using System;
    using System.Linq;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAI_Autosaver.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already launched.
        /// </summary>
        internal static string AlreadyLaunched {
            get {
                return ResourceManager.GetString("AlreadyLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup folder path is incorrect.
        /// </summary>
        internal static string IncorrectBackupPath {
            get {
                return ResourceManager.GetString("IncorrectBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is created but never saved locally.
        /// </summary>
        internal static string StateNeverSaved {
            get {
                return ResourceManager.GetString("StateNeverSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups disabled.
        /// </summary>
        internal static string StateSavingDisabled {
            get {
                return ResourceManager.GetString("StateSavingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is now saving your progress :&gt;.
        /// </summary>
        internal static string StateSavingEnabled {
            get {
                return ResourceManager.GetString("StateSavingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for a change of canvas.
        /// </summary>
        internal static string StateWaitingForCanvas {
            get {
                return ResourceManager.GetString("StateWaitingForCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAI is not launching.
        /// </summary>
        internal static string StateWaitingForProcess {
            get {
                return ResourceManager.GetString("StateWaitingForProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for a new project.
        /// </summary>
        internal static string StateWaitingForProject {
            get {
                return ResourceManager.GetString("StateWaitingForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour,hours,hours.
        /// </summary>
        internal static string[] TimeHour {
            get {
                return ResourceManager.GetString("TimeHour", resourceCulture).Split(',').ToArray();
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute,minutes,minutes.
        /// </summary>
        internal static string[] TimeMinute {
            get {
                return ResourceManager.GetString("TimeMinute", resourceCulture).Split(',').ToArray();
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second,seconds,seconds.
        /// </summary>
        internal static string[] TimeSecond {
            get {
                return ResourceManager.GetString("TimeSecond", resourceCulture).Split(',').ToArray();
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update available for SAI Autosaver..
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:.
        /// </summary>
        internal static string UpdateChangelog {
            get {
                return ResourceManager.GetString("UpdateChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update?.
        /// </summary>
        internal static string UpdateConfirm {
            get {
                return ResourceManager.GetString("UpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        internal static string UpdateCurrentVersion {
            get {
                return ResourceManager.GetString("UpdateCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string UpdateDone {
            get {
                return ResourceManager.GetString("UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update file.
        /// </summary>
        internal static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version: {0}.
        /// </summary>
        internal static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
    }
}
